### ISSUE TITLE
Is scaling supported?

### ISSUE THREAD

**Issue by a2geek** [blacksmith-community/mariadb-forge-boshrelease#15]
Is there a scaling mechanism available with the mariadb forge (or blacksmith) if my app grows out of the service plan?  

For instance, assume I start with a "small" database, fill that to capacity, and then want to bump the disk size.  Presumably the mechanism is to move to the next size, say "medium" database. Is that something this is capable of?  (bosh-wise, it would be likely swapping the VM and the usual persistent disk scaling. So I don't see it as technically infeasible. Just something that would need to be planned for in the manifest management.)

Thanks!

**Comment by jhunt** [comment]
This is best done by creating a new, bigger instance, and then using something like SHIELD, or mysqldump / xtrabackup to dump the database from the original instance, restore it to the bigger instance, and cut the app over.

**Comment by a2geek** [comment]
Hmm, ok.  I was thinking that. Not great, but it is functional.  Thanks!

**Comment by jhunt** [comment]
Save some CPIs that (now, and only very recently) support resizing underlying volumes, this is exactly how BOSH does it, but you have to wait for BOSH to copy over all of the raw files from the old persistent disk to the new persistent disk, and can't even keep the old software up in a read-only mode like you can with most data-centric backup tools.

**Comment by jhunt** [comment]
Oops.  wrong button.

**Comment by a2geek** [comment]
True. Good point re: availability. Closing intentionally this time. ;-)
