### ISSUE TITLE
Standalone plan hardcoded to only use 'z1' for AZ.

### ISSUE THREAD

**Issue by elric392** [blacksmith-community/mariadb-forge-boshrelease#3]
Trying to use this bosh release, and ran into issue with the availability zones configuration.

snippet from bosh manifest:

```
      - name:    mariadb-blacksmith-plans
        release: mariadb-forge
        properties:
          plans:
            b-mariadb-standalone:
              type:    standalone
              vm_type: t2.small
              network: dynamic-services
              azs:     us-east-1c
              disk:    8192
              limit:   10
```

But the 'azs' params are not being honored.  Regardless, the 'manifest' when creating a service, on that plan, always uses 'z1'.

**Comment by jhunt** [comment]
`azs` is not a valid property for the standalone plan.  As a workaround, you can set your cloud-config on your Blacksmith broker such that `z1` is in AWS' `us-east-1c`.

However, there is still value in making it configurable for cases where you want to run multiple services in different zones.

**Comment by elric392** [comment]
Was attempting to deploy this using the existing BOSH Director from my Pivotal foundation, which uses the format of _**REGION-#x**_ for defining/validation of the availability zones.  So it appears that I will have to deploy another BOSH director for the Blacksmith Broker to use, for the time being.

**Comment by jhunt** [comment]
We highly recommend putting Blacksmith on its own BOSH director anyway; normally we co-locate that director with the Blacksmith broker VM so that you don't eat another IP.

The [Genesis Kit for Blacksmith](https://github.com/genesis-community/blacksmith-genesis-kit) does just that, and allows you to set your cloud-config from the Genesis environment file.
